version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  api: &backend
    build:
      dockerfile: docker/Dockerfile.api
      context: .
    image: ghcr.io/aqudi/capstone_inobus_api
  rabbitmq:
    build:
      dockerfile: docker/Dockerfile.rabbitmq
      context: .
    image: ghcr.io/aqudi/capstone_inobus_rabbitmq
    ports:
      - 15672:15672 # For management
      - 5672:5672 # For AMQP
      - 18820:18820 # For MQTT
      - 9001:9001 # For websocket
  consumer:
    <<: *backend
    command: sh -c "./prestart.sh && python main_consumer.py"
    restart: unless-stopped
