version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build:
      dockerfile: docker/Dockerfile.api
      context: .
    image: ghcr.io/aqudi/capstone_inobus_api
    ports:
      - "80:8080"
