version: "3.8"

services:
  api:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: ghcr.io/aqudi/capstone_inobus_backend
    ports:
      - "80:8080"
    env_file:
      - envs/.env
    networks:
      - app

networks:
  app:
    driver: bridge
