version: "3.8"

services:
  api:
    extends:
      file: common.yaml
      service: api
    environment:
      - DB_NAME
      - DB_PASSWORD
      - DB_URL
      - DB_USERNAME
      - APP_PORT
      - APP_TEST
    depends_on:
      - rabbitmq
    networks:
      - app
  rabbitmq:
    extends:
      file: common.yaml
      service: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    networks:
      - app

networks:
  app:
    driver: bridge
