version: "3.8"

services:
  mongodb:
    extends:
      file: common.yaml
      service: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME="admin"
      - MONGO_INITDB_ROOT_PASSWORD="admin1234!"
      - MONGO_INITDB_DATABASE="next_generation"
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app
  api:
    extends:
      file: common.yaml
      service: api
    env_file:
      - envs/.env.api.local
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    networks:
      - app
    volumes:
      - .:/app
    command: "/start-reload.sh"

networks:
  app:
    driver: bridge

volumes:
  mongodb:
