version: "3.8"

services:
  api:
    extends:
      file: common.yaml
      service: api
    environment:
      - DOT_ENV=FALSE
      - DB_NAME
      - DB_PASSWORD
      - DB_URL
      - DB_USERNAME
      - PORT
    networks:
      - app

networks:
  app:
    driver: bridge
